site_name: scatterbrain
nav:
    - Home : README.md
    - Design Matrix API: design_matrix.md
    - ScatteredLightBackground API: background.md
    - StarScene API: scene.md
    - Data Flow Diagram : flowchart.md
    - Making asteroid masks: how-to-get-asteroid-masks.ipynb
    - Changelog : CHANGES.md

theme:
  name: "material"
  icon:
    logo: material/brain
  palette:
    scheme: default
    primary: red
    accent: blue
repo_url: https://github.com/christinahedges/scatterbrain
plugins:
  - include-markdown
  - search
  - mkdocs-jupyter:
      execute: False
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: false
      custom_templates: templates
      watch:
        - src/scatterbrain
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
